name:                hstamprally
version:             0.1.0.0
github:              "bouzuya/hstamprally"
license:             BSD3
author:              "bouzuya"
maintainer:          "m@bouzuya.net"
copyright:           "2018 bouzuya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/bouzuya/hstamprally#readme>

dependencies:
- base >= 4.7 && < 5
- uuid

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  hstamprally-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstamprally

tests:
  hstamprally-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstamprally
